// services/reportService.js
import { format } from "date-fns";
import jsPDF from "jspdf";
import "jspdf-autotable";

/**
 * Generate and download a PDF report for supervised teams or students
 * @param {Object} options Report options
 * @param {string} options.type Report type - 'teams', 'students', or 'projects'
 * @param {string} options.title Report title
 * @param {Array} options.data Data to include in the report
 * @param {Array} options.columns Column definitions
 * @param {Object} options.filters Any filters applied to the data
 * @param {string} options.supervisorName Name of the supervisor generating the report
 */
export const generatePdfReport = async (options) => {
  const { type, title, data, columns, filters = {}, supervisorName } = options;

  // Create a new PDF document
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Add report title
  doc.setFontSize(18);
  doc.text(title, pageWidth / 2, 20, { align: "center" });

  // Add report metadata
  doc.setFontSize(10);
  doc.text(`Generated by: ${supervisorName}`, 14, 30);
  doc.text(`Date: ${format(new Date(), "PPP")}`, 14, 35);

  // Add filters section if there are any filters
  if (Object.keys(filters).length > 0) {
    doc.text("Filters:", 14, 45);
    let yPos = 50;

    Object.entries(filters).forEach(([key, value]) => {
      if (value) {
        doc.text(`${key}: ${value}`, 20, yPos);
        yPos += 5;
      }
    });
  }

  // Prepare table data
  const tableData = data.map((item) => {
    return columns.map((col) => {
      // Handle nested properties with dot notation (e.g., 'user.name')
      if (col.key.includes(".")) {
        const keys = col.key.split(".");
        let value = item;

        for (const key of keys) {
          value = value?.[key];
          if (value === undefined) break;
        }

        return col.format ? col.format(value) : value || "";
      }

      // Handle regular properties
      return col.format ? col.format(item[col.key]) : item[col.key] || "";
    });
  });

  // Create table
  doc.autoTable({
    head: [columns.map((col) => col.header)],
    body: tableData,
    startY: Object.keys(filters).length > 0 ? 60 : 45,
    styles: { fontSize: 9 },
    headStyles: { fillColor: [75, 75, 100], textColor: [255, 255, 255] },
    alternateRowStyles: { fillColor: [240, 240, 245] },
    margin: { top: 60 },
  });

  // Add page footer
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.text(
      `Page ${i} of ${totalPages} - Generated on ${format(new Date(), "PPP")}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  // Download the PDF
  doc.save(`${type}-report-${format(new Date(), "yyyy-MM-dd")}.pdf`);

  return true;
};

/**
 * Generate and download a CSV report for supervised teams or students
 * @param {Object} options Report options
 * @param {string} options.type Report type
 * @param {Array} options.data Data to include in the report
 * @param {Array} options.columns Column definitions
 */
export const generateCsvReport = (options) => {
  const { type, data, columns } = options;

  // Create CSV headers
  let csv = columns.map((col) => `"${col.header}"`).join(",") + "\n";

  // Add data rows
  data.forEach((item) => {
    const row = columns
      .map((col) => {
        // Handle nested properties with dot notation
        if (col.key.includes(".")) {
          const keys = col.key.split(".");
          let value = item;

          for (const key of keys) {
            value = value?.[key];
            if (value === undefined) break;
          }

          return `"${col.format ? col.format(value) : value || ""}"`;
        }

        // Handle regular properties
        return `"${
          col.format ? col.format(item[col.key]) : item[col.key] || ""
        }"`;
      })
      .join(",");

    csv += row + "\n";
  });

  // Create a downloadable link
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.setAttribute("href", url);
  link.setAttribute(
    "download",
    `${type}-report-${format(new Date(), "yyyy-MM-dd")}.csv`
  );
  link.style.visibility = "hidden";
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  return true;
};

export default {
  generatePdfReport,
  generateCsvReport,
};
